name: beer_app
description: A Flutter beer app code challenge
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
